sonar.organization=gopocapp
sonar.projectKey=gopocapp
sonar.projectName=gopocapp

sonar.sources=.
sonar.exclusions=**/vendor/**,**/testdata/*

sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/vendor/**